version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    env_file:
      - .env.production.local
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - mongo
      - rabbitmq  # Adicionado o link para o serviço do RabbitMQ
    depends_on:
      - mongo
      - rabbitmq  # Adicionada dependência do serviço do RabbitMQ

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      DB_HOST: localhost
      DB_PORT: 27017
      DB_DATABASE: dev
    networks:
      - backend

  rabbitmq:  
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672" 
      - "15672:15672" 
    restart: "unless-stopped"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
